const actionTypes = {
  SET_GENDER: 'SET_GENDER',
  SET_CONSTITUTION: 'SET_CONSTITUTION',
  SET_EVENT: 'SET_EVENT',
  SET_TONE: 'SET_TONE',
  SET_PRICE_CATEGORY: 'SET_PRICE_CATEGORY'
}

export default actionTypes
