export default {
  SET_CATEGORY: 'SET_CATEGORY',
  SET_GENDER: 'SET_GENDER',
  SET_CONSTITUTION: 'SET_CONSTITUTION',
  SET_EVENT: 'SET_EVENT',
  SET_TONE: 'SET_TONE',
  SET_PRICE_CATEGORY: 'SET_PRICE_CATEGORY',
  INCREMENT_MODAL_STEP: 'INCREMENT_MODAL_STEP',
  DECREMENT_MODAL_STEP: 'DECREMENT_MODAL_STEP',
  RESET_TO_DEFAULT_MODAL_STATE: 'RESET_TO_DEFAULT_MODAL_STATE',
  RESET_TO_DEFAULT_FILTERS: 'RESET_TO_DEFAULT_FILTERS',
  
  SET_USER: 'SET_USER',

  SET_QUIZ_FINISHED: 'SET_QUIZ_FINISHED',

  SET_PRODUCTS: 'SET_PRODUCTS',

  INCREMENT_SHOW_ITEMS_IN_CATALOG: 'INCREMENT_SHOW_ITEMS_IN_CATALOG',
  RESET_SHOW_ITEMS_IN_CATALOG: 'RESET_SHOW_ITEMS_IN_CATALOG'
};
